export default [
  {
    image: "/img/about/kelechi.jpg",
    imagealt: "Kelechi J.Anunobi image",
    name: "Kelechi J.Anunobi",
    role: "C.E.O",
    facebooklink: "https://www.facebook.com/anunobik",
    twitterlink: " https://twitter.com/anunobik",
    linkedinlink: "https://www.linkedin.com/in/anunobik/",
  },
  {
    image: "/img/about/jackson.jpg",
    imagealt: "Amana Jackson image",
    name: "Amana Jackson",
    role: "C.O.O",
    facebooklink: "https://facebook.com/jacksonamana",
    twitterlink: "",
    linkedinlink: "https:// linkedin.com/in/jackson6",
  },
  {
    image: "/img/about/marisa.jpg",
    imagealt: "Marisa Attah image",
    name: "Marisa Attah",
    role: "Sales Manager",
    facebooklink: "https://facebook.com/MarisaTheBentley ",
    twitterlink: "",
    linkedinlink: "",
  },
  {
    image: "/img/about/johnimg.jpg",
    imagealt: "john idoko image",
    name: "John Idoko",
    role: "Frontend Engineering",
    facebooklink: "/facebook/john",
    twitterlink: "/twitter/john",
    linkedinlink: "/linkedin/john",
  },
];
